project:
  type: website
  resources:
    - images/

website:
  title: "Samiran Dutta"
  navbar: false

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: false
    css: styles.css
    section-divs: false
