project:
  type: website
  resources:
    - images/
    - googlee76222b4541bb231.html

website:
  title: "Samiran Dutta"
  navbar: false

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: false
    css: styles.css
    section-divs: false
    include-in-header:
      text: '<meta name="google-site-verification" content="e76222b4541bb231" />'
